### ISSUE TITLE
updating and increasing downloads

### ISSUE THREAD

**Issue by Erkatom** [eclipseisoffline/modifyplayerdata#3]
I really liked this mod. Firstly, I would really like it to be updated when 1.21.2 comes out (the sooner the better). And secondly, on one of the popular hosting sites it is written that this mod is not popular enough, so please make several versions at once (1.21, 1.21.1, 1.21.2), so that others will not have unnecessary questions and there will probably be more downloads .

**Comment by eclipseisoffline** [comment]
Hi, and thanks! I've been pretty busy over the last few weeks, with some real life stuff happening and a trip I went on, which is why the update to 1.21.1 (and other updates to my mods) has been delayed. I am back now though, and I'll try to keep my mods updated. As for this mod, it is a really small mod and so it is often very easy to update to newer versions. I might look towards publishing mod builds for snapshots.

As for the hosting sites you mention, I'm assuming you're referring to services as Aternos or the likes, and unfortunately there's not much I can do myself to have my mod be listed in their mod lists. Often a mod needs to have a certain amount of downloads to be able to be listed in their mod lists, and I myself can't really change that - however, do feel free to share this mod with people you know, and eventually it'll reach enough downloads to be listed.

**Comment by Erkatom** [comment]
Regarding hosting, the issue has already been resolved. As for updates, I’m glad that you don’t stop paying attention to your projects. I hope for your continued success. and thanks for the work!
